"""attest 观察管道 CLI。

用法：
  python observe.py <tool> <input...>              # 单输入 → 单报告
  python observe.py <tool> --generate-claims <input...>  # 建 claims 基线
"""
import argparse
import json
import pathlib

import yaml

from attest import build, parse, reconcile, report, rules, run

TOOLS_DIR = pathlib.Path("tools")


def load_manifest(tool: str) -> dict:
    p = TOOLS_DIR / tool / "tool.yaml"
    with open(p) as f:
        return yaml.safe_load(f)


def _drop_launch_execve(events: list[dict]) -> list[dict]:
    """剔除工具自身启动的 execve（第一条）。子进程 exec 保留——那才是真 exec。"""
    if events and events[0]["syscall"] in ("execve", "execveat"):
        return events[1:]
    return events


def observe(tool: str, inputs: list[str]) -> dict:
    manifest = load_manifest(tool)
    tool_dir = TOOLS_DIR / tool
    build.build_tool(manifest, tool_dir)
    text = run.run_tool(manifest, tool_dir, inputs)
    events = _drop_launch_execve(parse.parse_strace(text))
    for e in events:
        e["class"] = rules.classify(e["syscall"], e["args"])
    violations = reconcile.reconcile(events, manifest["claims"])
    return report.build_report(
        manifest["name"], inputs, manifest["claims"], events, violations
    )


def generate_claims(tool: str, inputs: list[str]) -> None:
    manifest = load_manifest(tool)
    tool_dir = TOOLS_DIR / tool
    build.build_tool(manifest, tool_dir)
    text = run.run_tool(manifest, tool_dir, inputs)
    events = _drop_launch_execve(parse.parse_strace(text))
    for e in events:
        e["class"] = rules.classify(e["syscall"], e["args"])

    observed = sorted({e["class"] for e in events})
    known = set(rules.SEVERITY)
    # other 永远不允许进 allow——它是未知行为，默认拒绝的兜底
    allow = [c for c in observed if c != "other"]
    deny = sorted((known - set(allow)) | {"other"})
    claims = {"allow": allow, "deny": deny}

    manifest["claims"] = claims
    p = TOOLS_DIR / tool / "tool.yaml"
    with open(p, "w") as f:
        f.write("# claims auto-generated by observe.py --generate-claims\n")
        yaml.safe_dump(manifest, f, allow_unicode=True, sort_keys=False)
    print(json.dumps(claims, ensure_ascii=False, indent=2))
    print(f"written to {p}")


def main() -> None:
    ap = argparse.ArgumentParser(prog="observe")
    ap.add_argument("tool", help="tools/ 下的工具名")
    ap.add_argument("inputs", nargs="*", default=[])
    ap.add_argument("--generate-claims", action="store_true")
    args = ap.parse_args()

    if args.generate_claims:
        generate_claims(args.tool, args.inputs)
        return
    r = observe(args.tool, args.inputs)
    print(json.dumps(r, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
