"""attest 观察管道 CLI。

用法：
  python observe.py <tool> <input...>              # 单输入 → 单报告
  python observe.py <tool> --generate-claims <input...>  # 建 claims 基线
"""
import argparse
import json
import pathlib

import yaml

from attest import build, parse, prereq, provenance, reconcile, report, rules, run

TOOLS_DIR = pathlib.Path("tools")


def load_manifest(tool: str) -> dict:
    p = TOOLS_DIR / tool / "tool.yaml"
    with open(p) as f:
        return yaml.safe_load(f)


def _drop_launch_execve(events: list[dict]) -> list[dict]:
    """剔除工具自身启动的 execve（第一条）。子进程 exec 保留——那才是真 exec。"""
    if events and events[0]["syscall"] in ("execve", "execveat"):
        return events[1:]
    return events


def annotate(events: list[dict]) -> None:
    """给事件标注 class（及 file-write 的 path/mode）。就地修改。"""
    for e in events:
        e["class"] = rules.classify(e["syscall"], e["args"])
        if e["class"] == "file-write":
            e["path"], e["mode"] = rules.write_attrs(e["syscall"], e["args"])
        if e["class"] == "network":
            e["ip"], e["port"] = rules.net_attrs(e["args"])
    rules.route_fds(events)  # 状态化 fd 路由：socket fd 的 write/read 归正为 network


def observe(tool: str, inputs: list[str]) -> dict:
    manifest = load_manifest(tool)
    tool_dir = TOOLS_DIR / tool
    build.build_tool(manifest, tool_dir)
    text = run.run_tool(manifest, tool_dir, inputs)
    events = _drop_launch_execve(parse.parse_strace(text))
    annotate(events)
    violations = reconcile.reconcile(events, manifest["claims"])
    return report.build_report(
        manifest["name"], inputs, manifest["claims"], events, violations,
        provenance=provenance.snapshot(manifest),
    )


def save_report(tool: str, r: dict) -> pathlib.Path:
    """把体检报告落盘到 tools/<tool>/report.json —— gate 读这份缓存做决策。"""
    p = TOOLS_DIR / tool / "report.json"
    p.write_text(json.dumps(r, ensure_ascii=False, indent=2))
    print(f"report written to {p}")
    return p


def generate_claims(tool: str, inputs: list[str]) -> None:
    manifest = load_manifest(tool)
    tool_dir = TOOLS_DIR / tool
    build.build_tool(manifest, tool_dir)
    text = run.run_tool(manifest, tool_dir, inputs)
    events = _drop_launch_execve(parse.parse_strace(text))
    annotate(events)

    observed = sorted({e["class"] for e in events})
    known = set(rules.SEVERITY)
    # other 永远不允许进 allow——它是未知行为，默认拒绝的兜底
    allow = [c for c in observed if c != "other"]

    # file-write 结构化：聚合路径 + 严上限 mode
    fw = [e for e in events if e["class"] == "file-write" and e.get("path")]
    if fw:
        import posixpath

        paths = sorted({posixpath.dirname(e["path"]) or "/" for e in fw})
        modes = {e.get("mode") for e in fw}
        if "overwrite" in modes:
            mode = "overwrite"
        elif "append" in modes:
            mode = "append"
        else:
            mode = "create"
        allow = [c for c in allow if c != "file-write"]
        allow.append({"class": "file-write", "mode": mode, "paths": paths})

    deny = sorted((known - set(observed)) | {"other"})
    claims = {"allow": allow, "deny": deny}

    manifest["claims"] = claims
    p = TOOLS_DIR / tool / "tool.yaml"
    with open(p, "w") as f:
        f.write("# claims auto-generated by observe.py --generate-claims\n")
        yaml.safe_dump(manifest, f, allow_unicode=True, sort_keys=False)
    print(json.dumps(claims, ensure_ascii=False, indent=2))
    print(f"written to {p}")


def generate_requires(tool: str, inputs: list[str]) -> None:
    """从一次观察运行推断工具的真实前置条件(requires)并写回 tool.yaml。"""
    manifest = load_manifest(tool)
    tool_dir = TOOLS_DIR / tool
    build.build_tool(manifest, tool_dir)
    text = run.run_tool(manifest, tool_dir, inputs)
    events = _drop_launch_execve(parse.parse_strace(text))
    annotate(events)

    # file-write 声明的白名单路径 = 工具需要在宿主可写的区域 → requires.writable
    writable = []
    for a in manifest.get("claims", {}).get("allow", []):
        if isinstance(a, dict) and a.get("class") == "file-write":
            writable += a.get("paths") or []
    inferred = prereq.infer_requires_full(events, writable)

    # 合并而非覆盖：env/cwd 无法从 strace 推断，保留手动声明；
    # exec 手动词条(python3)在推断为空时也保留。
    old = manifest.get("requires") or {}
    requires = {
        "env": old.get("env") or [],
        "files": inferred.get("files") or [],
        "exec": inferred.get("exec") or old.get("exec") or [],
        "writable": inferred.get("writable") or [],
    }
    if old.get("cwd"):
        requires["cwd"] = old["cwd"]

    manifest["requires"] = requires
    p = TOOLS_DIR / tool / "tool.yaml"
    with open(p, "w") as f:
        f.write("# requires auto-generated by observe.py --generate-requires\n")
        yaml.safe_dump(manifest, f, allow_unicode=True, sort_keys=False)
    print(json.dumps(requires, ensure_ascii=False, indent=2))
    print(f"written to {p}")


def check_requires(tool: str, inputs: list[str]) -> dict:
    """上岗前 pre-flight：硬校验 tool.yaml 的 requires。缺任一 → fail。"""
    manifest = load_manifest(tool)
    check = prereq.hard_check(manifest.get("requires"), cwd=str(TOOLS_DIR / tool))
    print(json.dumps(check, ensure_ascii=False, indent=2))
    return check


def main() -> None:
    ap = argparse.ArgumentParser(prog="observe")
    ap.add_argument("tool", help="tools/ 下的工具名")
    ap.add_argument("inputs", nargs="*", default=[])
    ap.add_argument("--generate-claims", action="store_true")
    ap.add_argument("--generate-requires", action="store_true")
    ap.add_argument("--check-requires", action="store_true")
    ap.add_argument("--save-report", action="store_true",
                    help="把报告落盘到 tools/<tool>/report.json(gate 决策缓存)")
    args = ap.parse_args()

    if args.generate_claims:
        generate_claims(args.tool, args.inputs)
        return
    if args.generate_requires:
        generate_requires(args.tool, args.inputs)
        return
    if args.check_requires:
        check_requires(args.tool, args.inputs)
        return
    r = observe(args.tool, args.inputs)
    print(json.dumps(r, ensure_ascii=False, indent=2))
    if args.save_report:
        save_report(args.tool, r)


if __name__ == "__main__":
    main()
